ALTER TABLE IF EXISTS empleado DROP FOREIGN KEY IF EXISTS fk_departamento;
ALTER TABLE IF EXISTS departamento DROP FOREIGN KEY IF EXISTS fk_jefe;
DROP TABLE IF EXISTS empleado;
DROP TABLE IF EXISTS departamento;